version: 2

sources:
   - name: public
     description: Rental data on Snowflake
     database: dvdrental
     tables:
        - name: customer
          description: '{{ doc("customer_table") }}'
          columns:
            - name: customer_id
              description: primary key for customers
              tests:
                - unique
                - not_null
            - name: first_name
              description: first name of customers


        - name: address
          description: '{{ doc("address_table") }}'
          columns:
            - name: address_id
              description: primary key for customers address
              tests:
                - unique
                - not_null
            - name: address
              description: first line of customers address

        - name: city
          description: '{{ doc("city_table") }}'
          columns:
            - name: city_id
              description: primary key for customers city of residence
              tests:
                - unique
                - not_null
            - name: city
              description: Name of city customers live

        - name: country
          description: '{{ doc("country_table") }}'
          columns:
            - name: country_id
              description: primary key for customers country of residence
              tests:
                - unique
                - not_null
            - name: country
              description: Name of country customers live

        - name: payment
          description: '{{ doc("payment_table") }}'
          columns:
            - name: payment_id
              description: primary key for customers payment transactions
              tests:
                - unique
                - not_null

        - name: film
          description: '{{ doc("film_table") }}'
          columns:
            - name: film_id
              description: primary key for rental films
              tests:
                - unique
                - not_null

        - name: inventory
          description: '{{ doc("inventory_table") }}'
          columns:
            - name: inventory_id
              description: primary key for all inventories
              tests:
                - unique
                - not_null

        - name: rental
          description: '{{ doc("rental_table") }}'
          columns:
            - name: rental_id
              description: primary key for all rentals
              tests:
                - unique
                - not_null

        - name: category
          description: '{{ doc("category_table") }}'
          columns:
            - name: category_id
              description: primary key for all rented film categories
              tests:
                - unique
                - not_null
            - name: name
              description: Name of rented film categories

        - name: film_category
          description: '{{ doc("film_category_table") }}'
          columns:
            - name: film_id
              description: primary key for film categories
              tests:
                - unique
                - not_null